readyset-server: controller->replicator channel
readysettech/readyset pull request #618
Opened 2023-09-18 17:57 UTC by altmannmarcelo

Added a new channel to exchange communication between controller->replicator.

The new ControllerMessage::ResnapshotTable is meant to propagate message informing the replicator the specific table has to be dropped and resnapshotted.

Next steps: 
1. Read the channel messages at noria_adapter.rs::main_loop and act accordingly
3. Send ControllerMessage::ResnapshotTable at [drop_snapshot_query](https://github.com/altmannmarcelo/readyset/blob/issue-456-parse/readyset-adapter/src/backend.rs#L1716)

2023-09-19 22:33 UTC, glittershark approved these changes
lgtm!

2023-09-19 22:58 UTC, glittershark requested changes
```
error[E0061]: this function takes 7 arguments but 6 arguments were supplied
   --> replicators/tests/tests.rs:357:33
    |
357 |             if let Err(error) = NoriaAdapter::start(
    |                                 ^^^^^^^^^^^^^^^^^^^
...
364 |                 telemetry_sender,
    |                 ---------------- an argument of type `&UnboundedReceiver<ControllerMessage>` is missing
    |
note: associated function defined here
   --> /readyset/readyset/public/replicators/src/noria_adapter.rs:162:18
    |
162 |     pub async fn start(
    |                  ^^^^^
help: provide the argument
    |
357 ~             if let Err(error) = NoriaAdapter::start(controller, Config {
358 +                     upstream_db_url: Some(url),
359 +                     ..config.unwrap_or_default()
360 +                 }, sender, /* &UnboundedReceiver<ControllerMessage> */, telemetry_sender, false, server_startup)
    |

For more information about this error, try `rustc --explain E0061`.
```

2023-09-20 01:46 UTC, altmannmarcelo commented
@glittershark I forgot about `cargo test` . It's fixed now.

2023-09-26 13:41 UTC, glittershark commented
Merged as https://github.com/readysettech/readyset/commit/6b14b4ba394dfcb89a99a8d2464b48a876430049

2023-09-26 13:41 UTC, closed without merging